version: '3.1'

services:

  finance-api:
    image: finance-api:latest
    container_name: finance-api
    ports:
      - "80:80"
    env_file:
      - ../.env
    restart: always

  mongo:
    image: mongo
    restart: always
    env_file:
      - ../.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ../.env
